# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import dica_pb2 as dica__pb2


class PartidaServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CriarJogador = channel.unary_unary(
                '/configuration.PartidaService/CriarJogador',
                request_serializer=dica__pb2.NomeJogador.SerializeToString,
                response_deserializer=dica__pb2.NomeJogadorResp.FromString,
                )
        self.EscolherPalavra = channel.unary_unary(
                '/configuration.PartidaService/EscolherPalavra',
                request_serializer=dica__pb2.Palavra.SerializeToString,
                response_deserializer=dica__pb2.PalavraResp.FromString,
                )
        self.VerPalavra = channel.unary_unary(
                '/configuration.PartidaService/VerPalavra',
                request_serializer=dica__pb2.MensagemVazia.SerializeToString,
                response_deserializer=dica__pb2.Palavra.FromString,
                )
        self.RecebeDica = channel.unary_unary(
                '/configuration.PartidaService/RecebeDica',
                request_serializer=dica__pb2.Dica.SerializeToString,
                response_deserializer=dica__pb2.MensagemVazia.FromString,
                )
        self.RecebePalpite = channel.unary_unary(
                '/configuration.PartidaService/RecebePalpite',
                request_serializer=dica__pb2.Palpite.SerializeToString,
                response_deserializer=dica__pb2.PalpiteResposta.FromString,
                )


class PartidaServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CriarJogador(self, request, context):
        """Recebe o nome dos jogadores
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EscolherPalavra(self, request, context):
        """Define a palavra que será adivinhada na partida
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def VerPalavra(self, request, context):
        """O jogador que fornece a dica deve receber a palavra
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RecebeDica(self, request, context):
        """recebe a dica do jogador 
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RecebePalpite(self, request, context):
        """recebe o palpite do jogador
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PartidaServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CriarJogador': grpc.unary_unary_rpc_method_handler(
                    servicer.CriarJogador,
                    request_deserializer=dica__pb2.NomeJogador.FromString,
                    response_serializer=dica__pb2.NomeJogadorResp.SerializeToString,
            ),
            'EscolherPalavra': grpc.unary_unary_rpc_method_handler(
                    servicer.EscolherPalavra,
                    request_deserializer=dica__pb2.Palavra.FromString,
                    response_serializer=dica__pb2.PalavraResp.SerializeToString,
            ),
            'VerPalavra': grpc.unary_unary_rpc_method_handler(
                    servicer.VerPalavra,
                    request_deserializer=dica__pb2.MensagemVazia.FromString,
                    response_serializer=dica__pb2.Palavra.SerializeToString,
            ),
            'RecebeDica': grpc.unary_unary_rpc_method_handler(
                    servicer.RecebeDica,
                    request_deserializer=dica__pb2.Dica.FromString,
                    response_serializer=dica__pb2.MensagemVazia.SerializeToString,
            ),
            'RecebePalpite': grpc.unary_unary_rpc_method_handler(
                    servicer.RecebePalpite,
                    request_deserializer=dica__pb2.Palpite.FromString,
                    response_serializer=dica__pb2.PalpiteResposta.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'configuration.PartidaService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class PartidaService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CriarJogador(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/configuration.PartidaService/CriarJogador',
            dica__pb2.NomeJogador.SerializeToString,
            dica__pb2.NomeJogadorResp.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def EscolherPalavra(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/configuration.PartidaService/EscolherPalavra',
            dica__pb2.Palavra.SerializeToString,
            dica__pb2.PalavraResp.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def VerPalavra(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/configuration.PartidaService/VerPalavra',
            dica__pb2.MensagemVazia.SerializeToString,
            dica__pb2.Palavra.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def RecebeDica(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/configuration.PartidaService/RecebeDica',
            dica__pb2.Dica.SerializeToString,
            dica__pb2.MensagemVazia.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def RecebePalpite(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/configuration.PartidaService/RecebePalpite',
            dica__pb2.Palpite.SerializeToString,
            dica__pb2.PalpiteResposta.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
