# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dica.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='dica.proto',
  package='configuration',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\ndica.proto\x12\rconfiguration\"\x1b\n\x0bNomeJogador\x12\x0c\n\x04nome\x18\x01 \x01(\t\"1\n\x0fNomeJogadorResp\x12\x0c\n\x04nome\x18\x01 \x01(\t\x12\x10\n\x08recebida\x18\x02 \x01(\x08\"\x1a\n\x07Palavra\x12\x0f\n\x07palavra\x18\x01 \x01(\t\"0\n\x0bPalavraResp\x12\x0f\n\x07palavra\x18\x01 \x01(\t\x12\x10\n\x08recebida\x18\x02 \x01(\x08\"\x14\n\x04\x44ica\x12\x0c\n\x04\x64ica\x18\x01 \x01(\t\"\x1a\n\x07Palpite\x12\x0f\n\x07palpite\x18\x01 \x01(\t\"E\n\x0fPalpiteResposta\x12\x0f\n\x07\x61\x63\x65rtou\x18\x01 \x01(\x08\x12\x10\n\x08mensagem\x18\x02 \x01(\t\x12\x0f\n\x07recebeu\x18\x03 \x01(\x08\"\x0f\n\rMensagemVazia2\xfb\x02\n\x0ePartidaService\x12L\n\x0c\x43riarJogador\x12\x1a.configuration.NomeJogador\x1a\x1e.configuration.NomeJogadorResp\"\x00\x12G\n\x0f\x45scolherPalavra\x12\x16.configuration.Palavra\x1a\x1a.configuration.PalavraResp\"\x00\x12\x44\n\nVerPalavra\x12\x1c.configuration.MensagemVazia\x1a\x16.configuration.Palavra\"\x00\x12\x41\n\nRecebeDica\x12\x13.configuration.Dica\x1a\x1c.configuration.MensagemVazia\"\x00\x12I\n\rRecebePalpite\x12\x16.configuration.Palpite\x1a\x1e.configuration.PalpiteResposta\"\x00\x62\x06proto3'
)




_NOMEJOGADOR = _descriptor.Descriptor(
  name='NomeJogador',
  full_name='configuration.NomeJogador',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='nome', full_name='configuration.NomeJogador.nome', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=29,
  serialized_end=56,
)


_NOMEJOGADORRESP = _descriptor.Descriptor(
  name='NomeJogadorResp',
  full_name='configuration.NomeJogadorResp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='nome', full_name='configuration.NomeJogadorResp.nome', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='recebida', full_name='configuration.NomeJogadorResp.recebida', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=58,
  serialized_end=107,
)


_PALAVRA = _descriptor.Descriptor(
  name='Palavra',
  full_name='configuration.Palavra',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='palavra', full_name='configuration.Palavra.palavra', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=109,
  serialized_end=135,
)


_PALAVRARESP = _descriptor.Descriptor(
  name='PalavraResp',
  full_name='configuration.PalavraResp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='palavra', full_name='configuration.PalavraResp.palavra', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='recebida', full_name='configuration.PalavraResp.recebida', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=137,
  serialized_end=185,
)


_DICA = _descriptor.Descriptor(
  name='Dica',
  full_name='configuration.Dica',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='dica', full_name='configuration.Dica.dica', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=187,
  serialized_end=207,
)


_PALPITE = _descriptor.Descriptor(
  name='Palpite',
  full_name='configuration.Palpite',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='palpite', full_name='configuration.Palpite.palpite', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=209,
  serialized_end=235,
)


_PALPITERESPOSTA = _descriptor.Descriptor(
  name='PalpiteResposta',
  full_name='configuration.PalpiteResposta',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='acertou', full_name='configuration.PalpiteResposta.acertou', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='mensagem', full_name='configuration.PalpiteResposta.mensagem', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='recebeu', full_name='configuration.PalpiteResposta.recebeu', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=237,
  serialized_end=306,
)


_MENSAGEMVAZIA = _descriptor.Descriptor(
  name='MensagemVazia',
  full_name='configuration.MensagemVazia',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=308,
  serialized_end=323,
)

DESCRIPTOR.message_types_by_name['NomeJogador'] = _NOMEJOGADOR
DESCRIPTOR.message_types_by_name['NomeJogadorResp'] = _NOMEJOGADORRESP
DESCRIPTOR.message_types_by_name['Palavra'] = _PALAVRA
DESCRIPTOR.message_types_by_name['PalavraResp'] = _PALAVRARESP
DESCRIPTOR.message_types_by_name['Dica'] = _DICA
DESCRIPTOR.message_types_by_name['Palpite'] = _PALPITE
DESCRIPTOR.message_types_by_name['PalpiteResposta'] = _PALPITERESPOSTA
DESCRIPTOR.message_types_by_name['MensagemVazia'] = _MENSAGEMVAZIA
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

NomeJogador = _reflection.GeneratedProtocolMessageType('NomeJogador', (_message.Message,), {
  'DESCRIPTOR' : _NOMEJOGADOR,
  '__module__' : 'dica_pb2'
  # @@protoc_insertion_point(class_scope:configuration.NomeJogador)
  })
_sym_db.RegisterMessage(NomeJogador)

NomeJogadorResp = _reflection.GeneratedProtocolMessageType('NomeJogadorResp', (_message.Message,), {
  'DESCRIPTOR' : _NOMEJOGADORRESP,
  '__module__' : 'dica_pb2'
  # @@protoc_insertion_point(class_scope:configuration.NomeJogadorResp)
  })
_sym_db.RegisterMessage(NomeJogadorResp)

Palavra = _reflection.GeneratedProtocolMessageType('Palavra', (_message.Message,), {
  'DESCRIPTOR' : _PALAVRA,
  '__module__' : 'dica_pb2'
  # @@protoc_insertion_point(class_scope:configuration.Palavra)
  })
_sym_db.RegisterMessage(Palavra)

PalavraResp = _reflection.GeneratedProtocolMessageType('PalavraResp', (_message.Message,), {
  'DESCRIPTOR' : _PALAVRARESP,
  '__module__' : 'dica_pb2'
  # @@protoc_insertion_point(class_scope:configuration.PalavraResp)
  })
_sym_db.RegisterMessage(PalavraResp)

Dica = _reflection.GeneratedProtocolMessageType('Dica', (_message.Message,), {
  'DESCRIPTOR' : _DICA,
  '__module__' : 'dica_pb2'
  # @@protoc_insertion_point(class_scope:configuration.Dica)
  })
_sym_db.RegisterMessage(Dica)

Palpite = _reflection.GeneratedProtocolMessageType('Palpite', (_message.Message,), {
  'DESCRIPTOR' : _PALPITE,
  '__module__' : 'dica_pb2'
  # @@protoc_insertion_point(class_scope:configuration.Palpite)
  })
_sym_db.RegisterMessage(Palpite)

PalpiteResposta = _reflection.GeneratedProtocolMessageType('PalpiteResposta', (_message.Message,), {
  'DESCRIPTOR' : _PALPITERESPOSTA,
  '__module__' : 'dica_pb2'
  # @@protoc_insertion_point(class_scope:configuration.PalpiteResposta)
  })
_sym_db.RegisterMessage(PalpiteResposta)

MensagemVazia = _reflection.GeneratedProtocolMessageType('MensagemVazia', (_message.Message,), {
  'DESCRIPTOR' : _MENSAGEMVAZIA,
  '__module__' : 'dica_pb2'
  # @@protoc_insertion_point(class_scope:configuration.MensagemVazia)
  })
_sym_db.RegisterMessage(MensagemVazia)



_PARTIDASERVICE = _descriptor.ServiceDescriptor(
  name='PartidaService',
  full_name='configuration.PartidaService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=326,
  serialized_end=705,
  methods=[
  _descriptor.MethodDescriptor(
    name='CriarJogador',
    full_name='configuration.PartidaService.CriarJogador',
    index=0,
    containing_service=None,
    input_type=_NOMEJOGADOR,
    output_type=_NOMEJOGADORRESP,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='EscolherPalavra',
    full_name='configuration.PartidaService.EscolherPalavra',
    index=1,
    containing_service=None,
    input_type=_PALAVRA,
    output_type=_PALAVRARESP,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='VerPalavra',
    full_name='configuration.PartidaService.VerPalavra',
    index=2,
    containing_service=None,
    input_type=_MENSAGEMVAZIA,
    output_type=_PALAVRA,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='RecebeDica',
    full_name='configuration.PartidaService.RecebeDica',
    index=3,
    containing_service=None,
    input_type=_DICA,
    output_type=_MENSAGEMVAZIA,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='RecebePalpite',
    full_name='configuration.PartidaService.RecebePalpite',
    index=4,
    containing_service=None,
    input_type=_PALPITE,
    output_type=_PALPITERESPOSTA,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_PARTIDASERVICE)

DESCRIPTOR.services_by_name['PartidaService'] = _PARTIDASERVICE

# @@protoc_insertion_point(module_scope)
