version: "3"

services: 
    server: 
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "50051:50051"
        command: python3 server.py
        volumes: 
            - .:/usr/app

    redis-compose:
        image: redis
        command: redis-server --appendonly yes
        hostname: redis
        ports:
            - "6379:6379"
        volumes:
            - .:/usr/app
