# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: config_rodada.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='config_rodada.proto',
  package='configuration',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x13\x63onfig_rodada.proto\x12\rconfiguration\"\x14\n\x04\x44ica\x12\x0c\n\x04\x64ica\x18\x01 \x01(\t\"\x1a\n\x07Palpite\x12\x0f\n\x07palpite\x18\x01 \x01(\t\"E\n\x0fPalpiteResposta\x12\x0f\n\x07\x61\x63\x65rtou\x18\x01 \x01(\x08\x12\x10\n\x08mensagem\x18\x02 \x01(\t\x12\x0f\n\x07recebeu\x18\x03 \x01(\x08\"\x0f\n\rMensagemVazia2\x9d\x01\n\rServicoRodada\x12\x41\n\nRecebeDica\x12\x13.configuration.Dica\x1a\x1c.configuration.MensagemVazia\"\x00\x12I\n\rRecebePalpite\x12\x16.configuration.Palpite\x1a\x1e.configuration.PalpiteResposta\"\x00\x62\x06proto3'
)




_DICA = _descriptor.Descriptor(
  name='Dica',
  full_name='configuration.Dica',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='dica', full_name='configuration.Dica.dica', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=38,
  serialized_end=58,
)


_PALPITE = _descriptor.Descriptor(
  name='Palpite',
  full_name='configuration.Palpite',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='palpite', full_name='configuration.Palpite.palpite', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=60,
  serialized_end=86,
)


_PALPITERESPOSTA = _descriptor.Descriptor(
  name='PalpiteResposta',
  full_name='configuration.PalpiteResposta',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='acertou', full_name='configuration.PalpiteResposta.acertou', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='mensagem', full_name='configuration.PalpiteResposta.mensagem', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='recebeu', full_name='configuration.PalpiteResposta.recebeu', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=88,
  serialized_end=157,
)


_MENSAGEMVAZIA = _descriptor.Descriptor(
  name='MensagemVazia',
  full_name='configuration.MensagemVazia',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=159,
  serialized_end=174,
)

DESCRIPTOR.message_types_by_name['Dica'] = _DICA
DESCRIPTOR.message_types_by_name['Palpite'] = _PALPITE
DESCRIPTOR.message_types_by_name['PalpiteResposta'] = _PALPITERESPOSTA
DESCRIPTOR.message_types_by_name['MensagemVazia'] = _MENSAGEMVAZIA
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Dica = _reflection.GeneratedProtocolMessageType('Dica', (_message.Message,), {
  'DESCRIPTOR' : _DICA,
  '__module__' : 'config_rodada_pb2'
  # @@protoc_insertion_point(class_scope:configuration.Dica)
  })
_sym_db.RegisterMessage(Dica)

Palpite = _reflection.GeneratedProtocolMessageType('Palpite', (_message.Message,), {
  'DESCRIPTOR' : _PALPITE,
  '__module__' : 'config_rodada_pb2'
  # @@protoc_insertion_point(class_scope:configuration.Palpite)
  })
_sym_db.RegisterMessage(Palpite)

PalpiteResposta = _reflection.GeneratedProtocolMessageType('PalpiteResposta', (_message.Message,), {
  'DESCRIPTOR' : _PALPITERESPOSTA,
  '__module__' : 'config_rodada_pb2'
  # @@protoc_insertion_point(class_scope:configuration.PalpiteResposta)
  })
_sym_db.RegisterMessage(PalpiteResposta)

MensagemVazia = _reflection.GeneratedProtocolMessageType('MensagemVazia', (_message.Message,), {
  'DESCRIPTOR' : _MENSAGEMVAZIA,
  '__module__' : 'config_rodada_pb2'
  # @@protoc_insertion_point(class_scope:configuration.MensagemVazia)
  })
_sym_db.RegisterMessage(MensagemVazia)



_SERVICORODADA = _descriptor.ServiceDescriptor(
  name='ServicoRodada',
  full_name='configuration.ServicoRodada',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=177,
  serialized_end=334,
  methods=[
  _descriptor.MethodDescriptor(
    name='RecebeDica',
    full_name='configuration.ServicoRodada.RecebeDica',
    index=0,
    containing_service=None,
    input_type=_DICA,
    output_type=_MENSAGEMVAZIA,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='RecebePalpite',
    full_name='configuration.ServicoRodada.RecebePalpite',
    index=1,
    containing_service=None,
    input_type=_PALPITE,
    output_type=_PALPITERESPOSTA,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_SERVICORODADA)

DESCRIPTOR.services_by_name['ServicoRodada'] = _SERVICORODADA

# @@protoc_insertion_point(module_scope)
