# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from partida import config_partida_pb2 as partida_dot_config__partida__pb2


class PartidaServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CriarJogador = channel.unary_unary(
                '/configuration.PartidaService/CriarJogador',
                request_serializer=partida_dot_config__partida__pb2.NomeJogador.SerializeToString,
                response_deserializer=partida_dot_config__partida__pb2.NomeJogadorResp.FromString,
                )
        self.EscolherPalavra = channel.unary_unary(
                '/configuration.PartidaService/EscolherPalavra',
                request_serializer=partida_dot_config__partida__pb2.Palavra.SerializeToString,
                response_deserializer=partida_dot_config__partida__pb2.PalavraResp.FromString,
                )
        self.VerPalavra = channel.unary_unary(
                '/configuration.PartidaService/VerPalavra',
                request_serializer=partida_dot_config__partida__pb2.MensagemVazia.SerializeToString,
                response_deserializer=partida_dot_config__partida__pb2.Palavra.FromString,
                )


class PartidaServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CriarJogador(self, request, context):
        """Recebe o nome dos jogadores
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EscolherPalavra(self, request, context):
        """Define a palavra que será adivinhada na partida
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def VerPalavra(self, request, context):
        """O jogador que fornece a dica deve receber a palavra
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PartidaServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CriarJogador': grpc.unary_unary_rpc_method_handler(
                    servicer.CriarJogador,
                    request_deserializer=partida_dot_config__partida__pb2.NomeJogador.FromString,
                    response_serializer=partida_dot_config__partida__pb2.NomeJogadorResp.SerializeToString,
            ),
            'EscolherPalavra': grpc.unary_unary_rpc_method_handler(
                    servicer.EscolherPalavra,
                    request_deserializer=partida_dot_config__partida__pb2.Palavra.FromString,
                    response_serializer=partida_dot_config__partida__pb2.PalavraResp.SerializeToString,
            ),
            'VerPalavra': grpc.unary_unary_rpc_method_handler(
                    servicer.VerPalavra,
                    request_deserializer=partida_dot_config__partida__pb2.MensagemVazia.FromString,
                    response_serializer=partida_dot_config__partida__pb2.Palavra.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'configuration.PartidaService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class PartidaService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CriarJogador(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/configuration.PartidaService/CriarJogador',
            partida_dot_config__partida__pb2.NomeJogador.SerializeToString,
            partida_dot_config__partida__pb2.NomeJogadorResp.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def EscolherPalavra(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/configuration.PartidaService/EscolherPalavra',
            partida_dot_config__partida__pb2.Palavra.SerializeToString,
            partida_dot_config__partida__pb2.PalavraResp.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def VerPalavra(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/configuration.PartidaService/VerPalavra',
            partida_dot_config__partida__pb2.MensagemVazia.SerializeToString,
            partida_dot_config__partida__pb2.Palavra.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
